# Generated by Django 3.1 on 2021-08-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_control', '0003_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
